gateway:
  host: srh00135.ute.fedex.com
  port: 8443
  protocol: https
clusterProperties:
  test.service.host: https://localhost:8444
  test.backend.url: sample-test
  hrt.ds.messagesize : 5000
  hrt.ds.windowvalue : 500
  hrt.ds.maxrequest : 500
